#!/bin/bash

# Decrypt the received data
openssl rsautl -decrypt -inkey ~/shrestha/private_key.pem -in ~/shrestha/secure_scheduled_file.enc -out ~/shrestha/decrypted_scheduled_file.txt

# Verify the signature
openssl dgst -sha256 -verify ~/shrestha/public_key_prachan.pem -signature ~/shrestha/scheduled_signature.bin ~/shrestha/secure_scheduled_file.enc
