#!/bin/bash

# Decrypt the data
openssl enc -d -aes-256-cbc -in ~/system2_folder/data.enc -out ~/system2_folder/decrypted_data.txt -pass file:~/system2_folder/symmetric.key

# Verify the signature
openssl dgst -sha256 -verify ~/system2_folder/system1_key.pub -signature ~/system2_folder/data.sig ~/system2_folder/decrypted_data.txt
