#!/bin/bash

# Generate file and sign it
echo "This is a scheduled file created at $(date)" > ~/folder1/scheduled_file.txt
openssl dgst -sha256 -sign ~/folder1/private_key.pem -out ~/folder1/scheduled_signature.bin ~/folder1/scheduled_file.txt

# Encrypt the data
openssl rsautl -encrypt -inkey ~/folder1/public_key_folder2.pem -pubin -in ~/folder1/scheduled_file.txt -out ~/folder1/secure_scheduled_file.enc

# Send the encrypted file and signature to folder2
scp ~/folder1/secure_scheduled_file.enc folder2@systemB:/home/folder2/folder2/
scp ~/folder1/scheduled_signature.bin folder2@systemB:/home/folder2/folder2/
